[2022-03-29 10:10:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:10:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:11:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:11:04] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4126,"PacketSent":3632,"PacketLost":0,"MessageReceived":400,"MessageSent":81,"LastMessageTime":1648519759,"DisconnectTimes":0,"LostTimes":0}},"time":1648519851}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:11:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:11:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:11:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:11:17] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4126,"PacketSent":3632,"PacketLost":0,"MessageReceived":400,"MessageSent":81,"LastMessageTime":1648519759,"DisconnectTimes":0,"LostTimes":0}},"time":1648519864}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:11:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:11:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:13:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:13:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:13:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:13:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:13:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:13:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:13:27] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":822612889,"message":"/market Mana 晓月灵砂","message_id":1246673871,"message_seq":431,"message_type":"group","post_type":"message","raw_message":"/market Mana 晓月灵砂","self_id":3102833903,"sender":{"age":0,"area":"","card":"","level":"","nickname":"普通人阿文","role":"owner","sex":"unknown","title":"","user_id":1270672343},"sub_type":"normal","time":1648519982,"user_id":1270672343}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:13:31] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4143,"PacketSent":3644,"PacketLost":0,"MessageReceived":403,"MessageSent":83,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648519986}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:13:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:13:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:13:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:13:56] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4147,"PacketSent":3647,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520011}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:14:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:14:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:14:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:14:20] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4148,"PacketSent":3648,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520036}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:14:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:14:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:14:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:14:45] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4149,"PacketSent":3649,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520060}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:14:50] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:14:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:15:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:15:09] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4151,"PacketSent":3651,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520085}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:15:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:15:21] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:15:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:15:34] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4151,"PacketSent":3651,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520109}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:15:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:15:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:15:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:15:58] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4152,"PacketSent":3652,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520134}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:16:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:16:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:16:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:16:23] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4153,"PacketSent":3653,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520158}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:16:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:16:34] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:16:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:16:48] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4154,"PacketSent":3654,"PacketLost":0,"MessageReceived":403,"MessageSent":84,"LastMessageTime":1648519983,"DisconnectTimes":0,"LostTimes":0}},"time":1648520183}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:16:53] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:16:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:17:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:53942->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 3 次重试 
[2022-03-29 10:43:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:43:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:43:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:43:59] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:44:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:44:06] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:44:08] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:44:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:44:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:44:19] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":822612889,"message":"魔导机械修理材料 /market 紫水栈桥","message_id":1150628861,"message_seq":439,"message_type":"group","post_type":"message","raw_message":"魔导机械修理材料 /market 紫水栈桥","self_id":3102833903,"sender":{"age":0,"area":"","card":"","level":"","nickname":"普通人阿文","role":"owner","sex":"unknown","title":"","user_id":1270672343},"sub_type":"normal","time":1648521834,"user_id":1270672343}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:44:21] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4255,"PacketSent":3727,"PacketLost":0,"MessageReceived":427,"MessageSent":88,"LastMessageTime":1648521834,"DisconnectTimes":0,"LostTimes":0}},"time":1648521836}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 停止上报：已达重试上线 
[2022-03-29 10:44:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:44:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:44:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 10:44:43] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4256,"PacketSent":3728,"PacketLost":0,"MessageReceived":427,"MessageSent":88,"LastMessageTime":1648521834,"DisconnectTimes":0,"LostTimes":0}},"time":1648521861}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:60887->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 停止上报：已达重试上线 
[2022-03-29 10:44:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:44:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:44:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:44:55] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4256,"PacketSent":3728,"PacketLost":0,"MessageReceived":427,"MessageSent":88,"LastMessageTime":1648521834,"DisconnectTimes":0,"LostTimes":0}},"time":1648521883}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:44:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:45:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:45:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:45:08] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4257,"PacketSent":3729,"PacketLost":0,"MessageReceived":427,"MessageSent":88,"LastMessageTime":1648521834,"DisconnectTimes":0,"LostTimes":0}},"time":1648521895}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:45:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:45:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:45:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:45:21] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4257,"PacketSent":3729,"PacketLost":0,"MessageReceived":427,"MessageSent":88,"LastMessageTime":1648521834,"DisconnectTimes":0,"LostTimes":0}},"time":1648521908}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:45:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:45:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2022-03-29 10:45:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:45:43] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2022-03-29 10:45:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:60922->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 3 次重试 
[2022-03-29 10:45:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:45:47] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":822612889,"message":"魔导机械修理材料 /market 紫水栈桥","message_id":1913134494,"message_seq":440,"message_type":"group","post_type":"message","raw_message":"魔导机械修理材料 /market 紫水栈桥","self_id":3102833903,"sender":{"age":0,"area":"","card":"","level":"","nickname":"普通人阿文","role":"owner","sex":"unknown","title":"","user_id":1270672343},"sub_type":"normal","time":1648521929,"user_id":1270672343}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:45:50] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4259,"PacketSent":3730,"PacketLost":0,"MessageReceived":428,"MessageSent":88,"LastMessageTime":1648521930,"DisconnectTimes":0,"LostTimes":0}},"time":1648521931}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:45:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:45:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:46:28] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:46:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:46:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:46:39] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4267,"PacketSent":3736,"PacketLost":0,"MessageReceived":429,"MessageSent":89,"LastMessageTime":1648521965,"DisconnectTimes":0,"LostTimes":0}},"time":1648521986}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:46:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:46:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:46:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 10:46:52] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4267,"PacketSent":3736,"PacketLost":0,"MessageReceived":429,"MessageSent":89,"LastMessageTime":1648521965,"DisconnectTimes":0,"LostTimes":0}},"time":1648521999}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 10:46:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 10:46:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 10:47:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:57:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:62384->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 1 次重试 
[2022-03-29 13:57:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:51338->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 1 次重试 
[2022-03-29 13:57:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:60593->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 2 次重试 
[2022-03-29 13:57:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:60592->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 2 次重试 
[2022-03-29 13:57:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 13:57:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 3 次重试 
[2022-03-29 13:57:58] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":675683939,"message":"/luck","message_id":478918209,"message_seq":441188,"message_type":"group","post_type":"message","raw_message":"/luck","self_id":3102833903,"sender":{"age":0,"area":"","card":"汤不理啵","level":"","nickname":"79","role":"owner","sex":"unknown","title":"⑨🐦","user_id":46025579},"sub_type":"normal","time":1648533456,"user_id":46025579}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:51936->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 停止上报：已达重试上线 
[2022-03-29 13:57:58] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4745,"PacketSent":4183,"PacketLost":0,"MessageReceived":456,"MessageSent":92,"LastMessageTime":1648533456,"DisconnectTimes":0,"LostTimes":0}},"time":1648533456}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:51935->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 停止上报：已达重试上线 
[2022-03-29 13:58:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:58:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:58:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:58:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:58:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:58:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:58:29] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4746,"PacketSent":4184,"PacketLost":0,"MessageReceived":456,"MessageSent":92,"LastMessageTime":1648533456,"DisconnectTimes":0,"LostTimes":0}},"time":1648533496}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:58:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:58:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:58:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:58:42] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4747,"PacketSent":4185,"PacketLost":0,"MessageReceived":456,"MessageSent":92,"LastMessageTime":1648533456,"DisconnectTimes":0,"LostTimes":0}},"time":1648533509}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:58:44] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:58:47] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:58:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:58:54] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4747,"PacketSent":4185,"PacketLost":0,"MessageReceived":456,"MessageSent":92,"LastMessageTime":1648533456,"DisconnectTimes":0,"LostTimes":0}},"time":1648533522}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:58:56] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:03] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:59:07] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4747,"PacketSent":4185,"PacketLost":0,"MessageReceived":456,"MessageSent":92,"LastMessageTime":1648533456,"DisconnectTimes":0,"LostTimes":0}},"time":1648533534}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:59:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:09] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:12] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:59:16] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:59:18] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":675683939,"message":"[CQ:image,file=3f96ac7900ae2df3e4cd91fc84abbbf0.image,url=https://gchat.qpic.cn/gchatpic_new/1712430536/675683939-2678186000-3F96AC7900AE2DF3E4CD91FC84ABBBF0/0?term=3,subType=0]","message_id":1804371671,"message_seq":441189,"message_type":"group","post_type":"message","raw_message":"[CQ:image,file=3f96ac7900ae2df3e4cd91fc84abbbf0.image,subType=0]","self_id":3102833903,"sender":{"age":0,"area":"","card":"Shuuka","level":"","nickname":"Shuuka","role":"member","sex":"unknown","title":"渣男","user_id":1712430536},"sub_type":"normal","time":1648533545,"user_id":1712430536}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:59:20] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4750,"PacketSent":4187,"PacketLost":0,"MessageReceived":457,"MessageSent":92,"LastMessageTime":1648533545,"DisconnectTimes":0,"LostTimes":0}},"time":1648533547}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:59:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:24] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:25] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-03-29 13:59:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:59:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:31] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-03-29 13:59:32] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3102833903,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":4750,"PacketSent":4187,"PacketLost":0,"MessageReceived":457,"MessageSent":92,"LastMessageTime":1648533545,"DisconnectTimes":0,"LostTimes":0}},"time":1648533560}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-03-29 13:59:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:56141->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 3 次重试 
[2022-03-29 13:59:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:56143->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 将进行第 1 次重试 
[2022-03-29 13:59:37] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":675683939,"message":"我luck呢","message_id":189468466,"message_seq":441190,"message_type":"group","post_type":"message","raw_message":"我luck呢","self_id":3102833903,"sender":{"age":0,"area":"","card":"汤不理啵","level":"","nickname":"79","role":"owner","sex":"unknown","title":"⑨🐦","user_id":46025579},"sub_type":"normal","time":1648533561,"user_id":46025579}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": read tcp 127.0.0.1:56142->127.0.0.1:8000: wsarecv: An existing connection was forcibly closed by the remote host. 停止上报：已达重试上线 
[2022-03-29 13:59:40] [WARNING]: 上报 Event 数据到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-03-29 13:59:40] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":675683939,"message":"/占卜","message_id":2085371812,"message_seq":441191,"message_type":"group","post_type":"message","raw_message":"/占卜","self_id":3102833903,"sender":{"age":0,"area":"","card":"汤不理啵","level":"","nickname":"79","role":"owner","sex":"unknown","title":"⑨🐦","user_id":46025579},"sub_type":"normal","time":1648533565,"user_id":46025579}
 到 http://127.0.0.1:8000/ 失败: Post "http://127.0.0.1:8000/": dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
